-- https://school.programmers.co.kr/learn/courses/30/lessons/59041
SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) >= 2
ORDER BY NAME
;

SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
WHERE NAME IN(SELECT B.NAME
FROM 
(SELECT NAME, COUNT(NAME) AS NAME_COUNT 
 FROM ANIMAL_INS GROUP BY NAME) 
B WHERE B.NAME_COUNT >= 2) 
GROUP BY NAME 
ORDER BY NAME
;