-- https://school.programmers.co.kr/learn/courses/30/lessons/59412

SELECT HOUR(AO.DATETIME) AS HOUR, COUNT(HOUR(AO.DATETIME))
FROM ANIMAL_OUTS AO
GROUP BY HOUR(AO.DATETIME)
HAVING HOUR >= 9 AND HOUR < 20
ORDER BY HOUR(AO.DATETIME);